### PR TITLE
Update Transformations.py

### PR DESCRIPTION
**Pull request by MohamadRZ4**

### CODE REVIEW

**Comment by MohamadRZ4** [comment]
# Reduced code duplication: The scale_mat function has been modified to handle scaling with one or three parameters. 
# Additionally, the apply_transform function was created to eliminate code repetition when combining matrices (local and global).
# Improved readability: Function and variable names have been simplified and made more logical, and parts of the code have been 
# refactored into more general and reusable functions.
# Better efficiency: np.eye is used for generating the identity matrix, which is more efficient and faster than manually creating the matrix.

**Comment by MatinAfzal** [comment]
Thank you for your changes, please register your request for beta, all changes will be committed on beta and after the relevant tests, they **will be merged with the new tag version on main**.

I will do my best to make GitHub's collaboration space brighter and more advanced.

**Comment by MatinAfzal** [comment]
Thank you for your changes, please register your request for beta, all changes will be committed on beta and after the relevant tests, they will be merged with the new tag version on main.

I will do my best to make GitHub's collaboration space brighter and more advanced.

**Comment by MatinAfzal** [comment]
> Reduced code duplication: The scale_mat function has been modified to handle scaling with one or three parameters. Additionally, the apply_transform function was created to eliminate code repetition when combining matrices (local and global). Improved readability: Function and variable names have been simplified and made more logical, and parts of the code have been refactored into more general and reusable functions. Better efficiency: np.eye is used for generating the identity matrix, which is more efficient and faster than manually creating the matrix.

Thank you for your changes, please register your request for beta, all changes will be committed on beta and after the relevant tests, they will be merged with the new tag version on main.

I will do my best to make GitHub's collaboration space brighter and more advanced.

**Pull request closed without merging**
